version: '3'

services:
  go:
    build: ./docker/go
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ../src:/src
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db-data:/var/lib/mysql
      - ./docker/db/my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local
