// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sample/migrations/ent/goal"
	"sample/migrations/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalCreate is the builder for creating a Goal entity.
type GoalCreate struct {
	config
	mutation *GoalMutation
	hooks    []Hook
}

// SetGoal sets the "goal" field.
func (gc *GoalCreate) SetGoal(s string) *GoalCreate {
	gc.mutation.SetGoal(s)
	return gc
}

// SetCreatedAt sets the "created_at" field.
func (gc *GoalCreate) SetCreatedAt(t time.Time) *GoalCreate {
	gc.mutation.SetCreatedAt(t)
	return gc
}

// SetUpdatedAt sets the "updated_at" field.
func (gc *GoalCreate) SetUpdatedAt(t time.Time) *GoalCreate {
	gc.mutation.SetUpdatedAt(t)
	return gc
}

// SetDeletedAt sets the "deleted_at" field.
func (gc *GoalCreate) SetDeletedAt(t time.Time) *GoalCreate {
	gc.mutation.SetDeletedAt(t)
	return gc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (gc *GoalCreate) SetNillableDeletedAt(t *time.Time) *GoalCreate {
	if t != nil {
		gc.SetDeletedAt(*t)
	}
	return gc
}

// SetID sets the "id" field.
func (gc *GoalCreate) SetID(i int) *GoalCreate {
	gc.mutation.SetID(i)
	return gc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (gc *GoalCreate) SetUserID(id int) *GoalCreate {
	gc.mutation.SetUserID(id)
	return gc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (gc *GoalCreate) SetNillableUserID(id *int) *GoalCreate {
	if id != nil {
		gc = gc.SetUserID(*id)
	}
	return gc
}

// SetUser sets the "user" edge to the User entity.
func (gc *GoalCreate) SetUser(u *User) *GoalCreate {
	return gc.SetUserID(u.ID)
}

// Mutation returns the GoalMutation object of the builder.
func (gc *GoalCreate) Mutation() *GoalMutation {
	return gc.mutation
}

// Save creates the Goal in the database.
func (gc *GoalCreate) Save(ctx context.Context) (*Goal, error) {
	var (
		err  error
		node *Goal
	)
	if len(gc.hooks) == 0 {
		if err = gc.check(); err != nil {
			return nil, err
		}
		node, err = gc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gc.check(); err != nil {
				return nil, err
			}
			gc.mutation = mutation
			if node, err = gc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gc.hooks) - 1; i >= 0; i-- {
			if gc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, gc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Goal)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from GoalMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GoalCreate) SaveX(ctx context.Context) *Goal {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GoalCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GoalCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GoalCreate) check() error {
	if _, ok := gc.mutation.Goal(); !ok {
		return &ValidationError{Name: "goal", err: errors.New(`ent: missing required field "Goal.goal"`)}
	}
	if _, ok := gc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Goal.created_at"`)}
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Goal.updated_at"`)}
	}
	return nil
}

func (gc *GoalCreate) sqlSave(ctx context.Context) (*Goal, error) {
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (gc *GoalCreate) createSpec() (*Goal, *sqlgraph.CreateSpec) {
	var (
		_node = &Goal{config: gc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: goal.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: goal.FieldID,
			},
		}
	)
	if id, ok := gc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := gc.mutation.Goal(); ok {
		_spec.SetField(goal.FieldGoal, field.TypeString, value)
		_node.Goal = value
	}
	if value, ok := gc.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := gc.mutation.UpdatedAt(); ok {
		_spec.SetField(goal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := gc.mutation.DeletedAt(); ok {
		_spec.SetField(goal.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if nodes := gc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   goal.UserTable,
			Columns: []string{goal.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoalCreateBulk is the builder for creating many Goal entities in bulk.
type GoalCreateBulk struct {
	config
	builders []*GoalCreate
}

// Save creates the Goal entities in the database.
func (gcb *GoalCreateBulk) Save(ctx context.Context) ([]*Goal, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Goal, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GoalCreateBulk) SaveX(ctx context.Context) []*Goal {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GoalCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GoalCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
